# Generated by Django 4.1.7 on 2023-02-23 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('photo_url', models.CharField(blank=True, max_length=500)),
                ('skill_set', models.CharField(blank=True, max_length=500)),
                ('profession', models.CharField(blank=True, max_length=500)),
                ('user_role', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
