# Generated by Django 4.1.7 on 2023-02-23 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('course_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('video_thumbnail_url', models.CharField(max_length=200)),
                ('video_playlist_url', models.CharField(max_length=200)),
            ],
        ),
    ]
