# Generated by Django 4.1.7 on 2023-02-23 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_heading', models.CharField(default='', max_length=200)),
                ('blog_body', models.TextField()),
                ('post_time', models.DateTimeField(auto_now_add=True)),
                ('post_update_time', models.DateTimeField(auto_now=True)),
                ('img_url', models.URLField(blank=True)),
                ('liked', models.IntegerField(default=0)),
                ('saved_by', models.EmailField(blank=True, max_length=254)),
                ('blog_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_post', to='users.user')),
            ],
        ),
    ]
