# Generated by Django 4.1.7 on 2023-02-23 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_heading', models.CharField(default='', max_length=200)),
                ('user_name', models.CharField(default='', max_length=100)),
                ('user_email', models.EmailField(default='', max_length=254)),
                ('blog_body', models.TextField()),
                ('liked', models.IntegerField(default=0)),
                ('post_time', models.DateField(auto_now=True)),
                ('saved_by', models.EmailField(blank=True, max_length=254)),
            ],
        ),
    ]
