# Generated by Django 4.1.7 on 2023-02-22 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmodel',
            name='user',
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='blog_heading',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='liked',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='post_time',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='saved_by',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='user_email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
