# Generated by Django 4.1.7 on 2023-02-22 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_blogmodel_user_blogmodel_blog_heading_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogmodel',
            old_name='blog',
            new_name='blog_body',
        ),
    ]
