# Generated by Django 4.1.7 on 2023-02-22 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_blog_blogmodel_blog_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='usee_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
