# Generated by Django 4.1.7 on 2023-02-22 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogmodel_usee_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogmodel',
            old_name='usee_name',
            new_name='user_name',
        ),
    ]
