# Generated by Django 4.1.7 on 2023-02-23 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_id'),
        ('blog', '0005_rename_usee_name_blogmodel_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmodel',
            name='user_email',
        ),
        migrations.RemoveField(
            model_name='blogmodel',
            name='user_name',
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='blog_creator',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='blog_post', to='users.user'),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='img_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='post_update_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='post_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
