# Generated by Django 4.1.7 on 2023-02-23 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_id'),
        ('blog', '0006_remove_blogmodel_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='blog_creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_post', to='users.user'),
        ),
    ]
