# Generated by Django 4.1.7 on 2023-02-23 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='skills',
            new_name='skill_requirements',
        ),
    ]
